# Generated by Django 3.1.4 on 2020-12-28 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField()),
                ('page_name', models.TextField()),
                ('page_fans', models.IntegerField()),
                ('page_url', models.URLField()),
                ('page_about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=1000, null=True)),
                ('post_photo', models.URLField()),
                ('post_message', models.TextField()),
                ('post_permalink', models.URLField()),
                ('post_likes_count', models.IntegerField()),
                ('post_shares_count', models.IntegerField()),
                ('post_reaction', models.IntegerField()),
                ('post_time', models.TextField()),
                ('page_fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagefid', to='fbapi.page')),
            ],
        ),
    ]
