# Generated by Django 3.1.4 on 2021-01-15 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=1000, null=True)),
                ('comment_message', models.TextField()),
                ('comment_reply', models.TextField()),
                ('comment_likes_count', models.IntegerField()),
                ('comment_reaction', models.IntegerField()),
                ('comment_time', models.TextField()),
                ('can_like', models.BooleanField()),
                ('can_remove', models.BooleanField()),
                ('comment_count', models.IntegerField()),
                ('can_comment', models.BooleanField()),
                ('is_private', models.BooleanField()),
                ('is_hidden', models.BooleanField()),
                ('can_hide', models.BooleanField()),
                ('posts_fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postsfid', to='fbapi.posts')),
            ],
        ),
    ]
