# Generated by Django 3.1.4 on 2021-01-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapi', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.CharField(max_length=1000, null=True)),
                ('reply_message', models.TextField()),
                ('reply_reply', models.TextField()),
                ('reply_likes_count', models.IntegerField()),
                ('reply_reaction', models.IntegerField()),
                ('reply_time', models.TextField()),
                ('can_like', models.BooleanField()),
                ('can_remove', models.BooleanField()),
                ('comment_count', models.IntegerField()),
                ('can_comment', models.BooleanField()),
                ('is_private', models.BooleanField()),
                ('is_hidden', models.BooleanField()),
                ('can_hide', models.BooleanField()),
                ('comment_fid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commentsfid', to='fbapi.comments')),
            ],
        ),
    ]
