# Generated by Django 3.1.4 on 2021-01-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapi', '0003_replys'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_from',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='replys',
            name='reply_from',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
