# Generated by Django 3.1.4 on 2021-01-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapi', '0004_auto_20210115_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_reaction',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_reply',
        ),
    ]
