# Generated by Django 3.1.4 on 2021-01-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapi', '0005_auto_20210115_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='is_spam',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='remaning',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='replys',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='replys',
            name='is_spam',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='replys',
            name='remaning',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
