# Generated by Django 3.1.4 on 2021-01-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapi', '0006_auto_20210127_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_permalink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_photo',
            field=models.URLField(null=True),
        ),
    ]
