# Generated by Django 3.1.4 on 2021-02-06 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fbapi', '0010_auto_20210201_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.CreateModel(
            name='FbProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FbuserId', models.IntegerField()),
                ('Fbusertoken', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='fbU_fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fbUfid', to='fbapi.fbprofile'),
        ),
    ]
