# Generated by Django 3.1.4 on 2021-02-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbapi', '0011_auto_20210206_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='page_fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagefidc', to='fbapi.page'),
        ),
    ]
